import { AcfFieldGroupDefinition } from "@/types/acf";

/**
 * Reviewable sample ACF field-group definition generated from the approved
 * inventory. Slice 1 scope: this is a reviewable export ONLY — nothing in
 * this slice calls WordPress to create or modify fields.
 */
export const sampleAcfFieldGroup: AcfFieldGroupDefinition = {
  key: "group_6a309dc6b_home_v1",
  title: "Home - Professional Services v1",
  fields: [
    {
      key: "field_hero_eyebrow",
      label: "Hero Eyebrow",
      name: "hero_eyebrow",
      type: "text",
      required: 0,
      maxlength: "120",
      instructions: "Small strategic highlighted text displayed above the main hero headline.",
    },
    {
      key: "field_hero_title",
      label: "Hero Title",
      name: "hero_title",
      type: "text",
      required: 1,
      maxlength: "120",
      instructions: "The primary headline for the webpage.",
    },
    {
      key: "field_hero_text",
      label: "Hero Sub-text",
      name: "hero_text",
      type: "textarea",
      required: 1,
      maxlength: "600",
      instructions: "Secondary paragraph text for the hero section.",
    },
    {
      key: "field_hero_button_text",
      label: "Hero Button Text",
      name: "hero_button_text",
      type: "text",
      required: 1,
      maxlength: "60",
    },
    {
      key: "field_hero_button_url",
      label: "Hero Button Destination URL",
      name: "hero_button_url",
      type: "url",
      required: 1,
    },
    {
      key: "field_hero_image",
      label: "Hero Image",
      name: "hero_image",
      type: "image",
      required: 0,
      return_format: "array",
      instructions: "An image to represent the business on the hero banner.",
    },
    {
      key: "field_about_eyebrow",
      label: "About Section Eyebrow",
      name: "about_eyebrow",
      type: "text",
      required: 0,
      maxlength: "120",
    },
    {
      key: "field_about_title",
      label: "About Section Title",
      name: "about_title",
      type: "text",
      required: 1,
      maxlength: "120",
    },
    {
      key: "field_about_text",
      label: "About Section Body Text",
      name: "about_text",
      type: "textarea",
      required: 1,
      maxlength: "1000",
    },
    {
      key: "field_services_section_eyebrow",
      label: "Services Section Eyebrow",
      name: "services_section_eyebrow",
      type: "text",
      required: 0,
      maxlength: "120",
    },
    {
      key: "field_services_section_title",
      label: "Services Section Title",
      name: "services_section_title",
      type: "text",
      required: 1,
      maxlength: "120",
    },
    {
      key: "field_services",
      label: "Services",
      name: "services",
      type: "repeater",
      layout: "block",
      button_label: "Add Service Card",
      instructions: "Define up to 12 services to showcase. Reorder cards by dragging them.",
      sub_fields: [
        {
          key: "field_service_title",
          label: "Service Title",
          name: "services_title",
          type: "text",
          required: 1,
          maxlength: "100",
        },
        {
          key: "field_service_description",
          label: "Service Description",
          name: "services_description",
          type: "textarea",
          required: 1,
          maxlength: "500",
        },
        {
          key: "field_service_url",
          label: "Service Detail URL",
          name: "services_url",
          type: "url",
          required: 0,
        },
      ],
    },
    {
      key: "field_faqs_section_eyebrow",
      label: "FAQs Section Eyebrow",
      name: "faqs_section_eyebrow",
      type: "text",
      required: 0,
      maxlength: "120",
    },
    {
      key: "field_faqs_section_title",
      label: "FAQs Section Title",
      name: "faqs_section_title",
      type: "text",
      required: 1,
      maxlength: "120",
    },
    {
      key: "field_faqs",
      label: "FAQs",
      name: "faqs",
      type: "repeater",
      layout: "row",
      button_label: "Add FAQ Accordion Item",
      sub_fields: [
        {
          key: "field_faq_question",
          label: "FAQ Question",
          name: "faqs_question",
          type: "text",
          required: 1,
          maxlength: "200",
        },
        {
          key: "field_faq_answer",
          label: "FAQ Answer",
          name: "faqs_answer",
          type: "textarea",
          required: 1,
          maxlength: "1000",
        },
      ],
    },
    {
      key: "field_contact_title",
      label: "Contact Headline",
      name: "contact_title",
      type: "text",
      required: 1,
      maxlength: "120",
    },
    {
      key: "field_contact_phone",
      label: "Contact Phone",
      name: "contact_phone",
      type: "text",
      required: 1,
      maxlength: "40",
    },
    {
      key: "field_contact_email",
      label: "Contact Email",
      name: "contact_email",
      type: "email",
      required: 1,
      maxlength: "100",
    },
    {
      key: "field_contact_address",
      label: "Contact Physical Address",
      name: "contact_address",
      type: "textarea",
      required: 0,
      maxlength: "300",
    },
    {
      key: "field_footer_copyright",
      label: "Footer Copyright",
      name: "footer_copyright",
      type: "text",
      required: 1,
      maxlength: "200",
    },
  ],
  location: [
    [
      {
        param: "page_type",
        operator: "==",
        value: "front_page",
      },
    ],
  ],
  active: true,
  description: "Generated by Haipa Labs Multi-Tenant website schema exporter for Slice 1. Reviewable sample only — no WordPress calls are made in this slice.",
};