import { ContentInventory } from "@/types/inventory";
import { homeFixture } from "./home.fixture";

/**
 * Explicit editable-content inventory for the approved Home template.
 * This is hand-maintained metadata (NOT derived from Zod internals):
 * path, label, type, editable, required, maxLength, wpName,
 * sourceComponent, defaultValue, and notes.
 */
export const contentInventory: ContentInventory[] = [
  {
    path: "hero.eyebrow",
    label: "Hero Eyebrow (Small text above title)",
    type: "text",
    editable: true,
    required: false,
    maxLength: 120,
    wpName: "hero_eyebrow",
    sourceComponent: "Hero.tsx",
    defaultValue: homeFixture.hero.eyebrow,
    notes: "A short strategic highlight or brand intro.",
  },
  {
    path: "hero.title",
    label: "Hero Main Title",
    type: "text",
    editable: true,
    required: true,
    maxLength: 120,
    wpName: "hero_title",
    sourceComponent: "Hero.tsx",
    defaultValue: homeFixture.hero.title,
    notes: "The primary bold headline on the homepage.",
  },
  {
    path: "hero.body",
    label: "Hero Sub-text Paragraph",
    type: "textarea",
    editable: true,
    required: true,
    maxLength: 600,
    wpName: "hero_text",
    sourceComponent: "Hero.tsx",
    defaultValue: homeFixture.hero.body,
    notes: "A paragraph that expands on the headline and company's value proposition.",
  },
  {
    path: "hero.primaryCta.label",
    label: "Hero CTA Button Label",
    type: "text",
    editable: true,
    required: true,
    maxLength: 60,
    wpName: "hero_button_text",
    sourceComponent: "Hero.tsx",
    defaultValue: homeFixture.hero.primaryCta.label,
    notes: "Label for the main call-to-action button.",
  },
  {
    path: "hero.primaryCta.href",
    label: "Hero CTA Button Destination URL",
    type: "url",
    editable: true,
    required: true,
    maxLength: 500,
    wpName: "hero_button_url",
    sourceComponent: "Hero.tsx",
    defaultValue: homeFixture.hero.primaryCta.href,
    notes: "Destination page or external link for the CTA button.",
  },
  {
    path: "hero.image",
    label: "Hero Background/Side Image",
    type: "image",
    editable: true,
    required: false,
    wpName: "hero_image",
    sourceComponent: "Hero.tsx",
    defaultValue: homeFixture.hero.image,
    notes: "High-quality brand image supporting the hero message.",
  },
  {
    path: "about.eyebrow",
    label: "About Section Eyebrow",
    type: "text",
    editable: true,
    required: false,
    maxLength: 120,
    wpName: "about_eyebrow",
    sourceComponent: "About.tsx",
    defaultValue: homeFixture.about.eyebrow,
    notes: "Label/header positioned above the main about title.",
  },
  {
    path: "about.title",
    label: "About Section Title",
    type: "text",
    editable: true,
    required: true,
    maxLength: 120,
    wpName: "about_title",
    sourceComponent: "About.tsx",
    defaultValue: homeFixture.about.title,
    notes: "Main header of the About Section.",
  },
  {
    path: "about.body",
    label: "About Section Content",
    type: "textarea",
    editable: true,
    required: true,
    maxLength: 1000,
    wpName: "about_text",
    sourceComponent: "About.tsx",
    defaultValue: homeFixture.about.body,
    notes: "A rich paragraph introducing the company philosophy and standard of work.",
  },
  {
    path: "services.eyebrow",
    label: "Services Section Eyebrow",
    type: "text",
    editable: true,
    required: false,
    maxLength: 120,
    wpName: "services_section_eyebrow",
    sourceComponent: "Services.tsx",
    defaultValue: homeFixture.services.eyebrow,
    notes: "Label positioned above the services section title.",
  },
  {
    path: "services.title",
    label: "Services Section Title",
    type: "text",
    editable: true,
    required: true,
    maxLength: 120,
    wpName: "services_section_title",
    sourceComponent: "Services.tsx",
    defaultValue: homeFixture.services.title,
    notes: "Main header of the services section.",
  },
  {
    path: "services.items",
    label: "Services Listing Repeater",
    type: "repeater",
    editable: true,
    required: false,
    wpName: "services",
    sourceComponent: "Services.tsx",
    defaultValue: homeFixture.services.items,
    notes: "A list of service items dynamically shown as cards. Maximum of 12 items.",
  },
  {
    path: "services[].title",
    label: "Service Card Title",
    type: "text",
    editable: true,
    required: true,
    maxLength: 100,
    wpName: "services_title",
    sourceComponent: "Services.tsx",
    defaultValue: "Service Title Example",
    notes: "Sub-field inside the Services repeater.",
  },
  {
    path: "services[].description",
    label: "Service Card Description",
    type: "textarea",
    editable: true,
    required: true,
    maxLength: 500,
    wpName: "services_description",
    sourceComponent: "Services.tsx",
    defaultValue: "Service description example explaining the capabilities and outcomes.",
    notes: "Sub-field inside the Services repeater.",
  },
  {
    path: "services[].href",
    label: "Service Card Detail URL",
    type: "url",
    editable: true,
    required: false,
    maxLength: 500,
    wpName: "services_url",
    sourceComponent: "Services.tsx",
    defaultValue: "#",
    notes: "Optional detail link sub-field inside the Services repeater.",
  },
  {
    path: "faqs.eyebrow",
    label: "FAQs Section Eyebrow",
    type: "text",
    editable: true,
    required: false,
    maxLength: 120,
    wpName: "faqs_section_eyebrow",
    sourceComponent: "Faq.tsx",
    defaultValue: homeFixture.faqs.eyebrow,
    notes: "Label positioned above the FAQs section title.",
  },
  {
    path: "faqs.title",
    label: "FAQs Section Title",
    type: "text",
    editable: true,
    required: true,
    maxLength: 120,
    wpName: "faqs_section_title",
    sourceComponent: "Faq.tsx",
    defaultValue: homeFixture.faqs.title,
    notes: "Main header of the FAQs section.",
  },
  {
    path: "faqs.items",
    label: "FAQs Repeater",
    type: "repeater",
    editable: true,
    required: false,
    wpName: "faqs",
    sourceComponent: "Faq.tsx",
    defaultValue: homeFixture.faqs.items,
    notes: "A list of frequently asked questions and corresponding answers. Maximum 20.",
  },
  {
    path: "faqs[].question",
    label: "FAQ Question",
    type: "text",
    editable: true,
    required: true,
    maxLength: 200,
    wpName: "faqs_question",
    sourceComponent: "Faq.tsx",
    defaultValue: "FAQ Question Example?",
    notes: "Sub-field inside the FAQ repeater.",
  },
  {
    path: "faqs[].answer",
    label: "FAQ Answer",
    type: "textarea",
    editable: true,
    required: true,
    maxLength: 1000,
    wpName: "faqs_answer",
    sourceComponent: "Faq.tsx",
    defaultValue: "FAQ answer explanation outlining business policies or terms.",
    notes: "Sub-field inside the FAQ repeater.",
  },
  {
    path: "contact.title",
    label: "Contact Section Headline",
    type: "text",
    editable: true,
    required: true,
    maxLength: 120,
    wpName: "contact_title",
    sourceComponent: "Contact.tsx",
    defaultValue: homeFixture.contact.title,
    notes: "Title encouraging potential clients to reach out.",
  },
  {
    path: "contact.phone",
    label: "Contact Phone Number",
    type: "phone",
    editable: true,
    required: true,
    maxLength: 40,
    wpName: "contact_phone",
    sourceComponent: "Contact.tsx",
    defaultValue: homeFixture.contact.phone,
    notes: "Main business phone contact number.",
  },
  {
    path: "contact.email",
    label: "Contact Email Address",
    type: "email",
    editable: true,
    required: true,
    maxLength: 100,
    wpName: "contact_email",
    sourceComponent: "Contact.tsx",
    defaultValue: homeFixture.contact.email,
    notes: "Primary business inquiry email address.",
  },
  {
    path: "contact.address",
    label: "Contact Physical Address",
    type: "textarea",
    editable: true,
    required: false,
    maxLength: 300,
    wpName: "contact_address",
    sourceComponent: "Contact.tsx",
    defaultValue: homeFixture.contact.address,
    notes: "Physical location or office address for in-person meetings.",
  },
  {
    path: "footer.copyright",
    label: "Footer Copyright String",
    type: "text",
    editable: true,
    required: true,
    maxLength: 200,
    wpName: "footer_copyright",
    sourceComponent: "Footer.tsx",
    defaultValue: homeFixture.footer.copyright,
    notes: "Standard copyright information shown at the bottom of the page.",
  },
  {
    path: "layout.spacing",
    label: "Theme Section Spacing System",
    type: "text",
    editable: false,
    required: true,
    wpName: "n_a",
    sourceComponent: "globals.css",
    defaultValue: "Standard spacing tokens (4rem to 8rem vertical margins)",
    notes: "Design-controlled spacing token. Changes to this must be made in the React code to protect the brand system.",
  },
  {
    path: "layout.colors",
    label: "Brand Colors (Primary, Secondary, Background)",
    type: "text",
    editable: false,
    required: true,
    wpName: "n_a",
    sourceComponent: "globals.css",
    defaultValue: "Deep Slate (#0f172a), Deep Sage (#0f766e), Premium Cream (#f8fafc)",
    notes: "Design-controlled brand colors. Locked in React stylesheets to ensure contrast and visual identity rules.",
  },
  {
    path: "layout.typography",
    label: "Typography Scale and Section Title Styling",
    type: "text",
    editable: false,
    required: true,
    wpName: "n_a",
    sourceComponent: "globals.css",
    defaultValue: "System sans-serif stack, 2.25rem section titles, 1.25 heading line-height",
    notes: "Design-controlled typography. Locked in React stylesheets to protect the visual hierarchy.",
  },
];